"""Fix transaction schema

Revision ID: 3723865c2a11
Revises: c6191a783cd0
Create Date: 2026-09-27 14:53:57.685185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3723865c2a11'
down_revision: Union[str, None] = 'c6191a783cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_items', sa.Column('stock_name', sa.String(), nullable=False))
    op.add_column('transaction_items', sa.Column('unit', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('discount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('tax', sa.Float(), nullable=False))
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'tax')
    op.drop_column('transactions', 'discount')
    op.drop_column('transactions', 'subtotal')
    op.drop_column('transaction_items', 'unit')
    op.drop_column('transaction_items', 'stock_name')
    # ### end Alembic commands ###
