"""Fix users table schema

Revision ID: 421c39a2948c
Revises: 38521cfbf8c7
Create Date: 2026-09-27 13:56:08.424465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421c39a2948c'
down_revision: Union[str, None] = '38521cfbf8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'name')
    op.drop_column('users', 'business_id')
    # ### end Alembic commands ###
