"""Fix invoice schema

Revision ID: 78271e54d332
Revises: 3723865c2a11
Create Date: 2026-09-27 14:57:58.436241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78271e54d332'
down_revision: Union[str, None] = '3723865c2a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('discount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('tax_rate', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('payment_status', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('payment_method', sa.String(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'payment_status')
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'tax_rate')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'customer_id')
    # ### end Alembic commands ###
