"""Fix businesses table schema

Revision ID: ad370010368f
Revises: 421c39a2948c
Create Date: 2026-09-27 14:02:25.615488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad370010368f'
down_revision: Union[str, None] = '421c39a2948c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('owner_user_id', sa.UUID(), nullable=False))
    op.add_column('businesses', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('email', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('address', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('invoice_prefix', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('logo_path', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=False)
    op.drop_column('businesses', 'currency')
    op.drop_column('businesses', 'owner_id')
    op.drop_column('businesses', 'gstin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('gstin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('businesses', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=False)
    op.drop_column('businesses', 'is_active')
    op.drop_column('businesses', 'logo_path')
    op.drop_column('businesses', 'invoice_prefix')
    op.drop_column('businesses', 'gst_number')
    op.drop_column('businesses', 'address')
    op.drop_column('businesses', 'email')
    op.drop_column('businesses', 'phone')
    op.drop_column('businesses', 'owner_name')
    op.drop_column('businesses', 'owner_user_id')
    # ### end Alembic commands ###
