"""Fix customers table schema

Revision ID: c6191a783cd0
Revises: ad370010368f
Create Date: 2026-09-27 14:51:08.973530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6191a783cd0'
down_revision: Union[str, None] = 'ad370010368f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('credit_limit', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('payment_terms_days', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.drop_column('customers', 'payment_terms_days')
    op.drop_column('customers', 'credit_limit')
    op.drop_column('customers', 'gst_number')
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'business_name')
    # ### end Alembic commands ###
